version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/raycast'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 2
    groups:
      all-npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
