import { rm, mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  addPrReviewDraftComment,
  readLivePrReviewDraft,
  upsertPrReviewDraft,
  type GitHubDiffSummary,
  type GitHubPullRequestEventState,
  type GitHubPullRequestFile,
} from './modules/github';
import {
  reviewPrForHuman,
  type ReviewAssistFacts,
} from './modules/pr-review-assist';
import { listReports, readReportHtml } from './modules/reports';
import { ensureRuntimeHome, runtimePaths } from './runtime-home';

const tempRoots: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempRoots
      .splice(0)
      .map((path) => rm(path, { recursive: true, force: true })),
  );
});

describe('PR review assist', () => {
  it('defaults human draft comment origin and preserves explicit Neon origin', async () => {
    const paths = await tempPaths();
    const draft = upsertPrReviewDraft({
      databasePath: paths.neondeckDatabase,
      repo: 'pandemicsyn/neondeck',
      prNumber: 10,
      headSha: 'head123',
    });

    const withHuman = addPrReviewDraftComment({
      databasePath: paths.neondeckDatabase,
      draftId: draft.id,
      path: 'src/app.ts',
      side: 'RIGHT',
      line: 2,
      body: 'Human draft',
    });
    const withNeon = addPrReviewDraftComment({
      databasePath: paths.neondeckDatabase,
      draftId: draft.id,
      path: 'src/app.ts',
      side: 'RIGHT',
      line: 3,
      body: 'Neon draft',
      origin: 'neon',
    });

    expect(withHuman.comments.at(-1)).toMatchObject({ origin: 'human' });
    expect(withNeon.comments.at(-1)).toMatchObject({ origin: 'neon' });
  });

  it('seeds only anchor-valid Neon draft comments and writes escaped reports', async () => {
    const paths = await tempPaths();
    const facts = reviewFacts();
    const result = await reviewPrForHuman(
      { ref: 'pandemicsyn/neondeck#10' },
      paths,
      {
        fetchFacts: async () => facts,
        reviewer: async () => ({
          overview: {
            summary: 'Review <script>alert(1)</script>',
            changeMap: [
              {
                path: 'src/app.ts',
                summary: 'Adds guarded branch with <unsafe> text.',
              },
            ],
            risks: ['Risk contains <b>markup</b>'],
            checks: ['unit tests pending'],
          },
          findings: [
            {
              severity: 'major',
              path: 'src/app.ts',
              side: 'RIGHT',
              line: 2,
              summary: 'Validate the new branch.',
              suggestedFix: 'Add an explicit guard.',
              confidence: 'high',
            },
            {
              severity: 'minor',
              path: 'src/app.ts',
              side: 'RIGHT',
              line: 200,
              summary: 'This cannot be anchored.',
              suggestedFix: 'Keep it report-only.',
            },
          ],
        }),
      },
    );

    const okResult = requireReviewAssistOk(result);
    expect(okResult.data).toMatchObject({
      findingCount: 2,
      seededCount: 1,
      reportOnlyCount: 1,
      skippedSeedingReason: null,
    });

    const draft = readLivePrReviewDraft({
      databasePath: paths.neondeckDatabase,
      repo: 'pandemicsyn/neondeck',
      prNumber: 10,
    });
    expect(draft?.comments).toMatchObject([
      {
        path: 'src/app.ts',
        line: 2,
        origin: 'neon',
        body: expect.stringContaining('Generated by Neon'),
      },
    ]);

    const reports = await listReports(paths, { kind: 'pr-review' });
    expect(reports).toHaveLength(2);
    const overview = reports.find((report) =>
      report.title.startsWith('PR Overview:'),
    );
    expect(overview).toBeTruthy();
    const html = await readReportHtml(overview!.id, paths);
    expect(html?.html).toContain(
      'Review &lt;script&gt;alert(1)&lt;/script&gt;',
    );
    expect(html?.html).toContain('Risk contains &lt;b&gt;markup&lt;/b&gt;');
    expect(html?.html).not.toContain('<script>alert(1)</script>');
  });

  it('does not overwrite or append to an existing human draft', async () => {
    const paths = await tempPaths();
    const draft = upsertPrReviewDraft({
      databasePath: paths.neondeckDatabase,
      repo: 'pandemicsyn/neondeck',
      prNumber: 10,
      headSha: 'head123',
      body: 'Human body',
    });
    addPrReviewDraftComment({
      databasePath: paths.neondeckDatabase,
      draftId: draft.id,
      path: 'src/app.ts',
      side: 'RIGHT',
      line: 2,
      body: 'Human inline comment',
    });

    const result = await reviewPrForHuman(
      { ref: 'pandemicsyn/neondeck#10' },
      paths,
      {
        fetchFacts: async () => reviewFacts(),
        reviewer: async () => reviewOutputWithOneFinding(),
      },
    );

    const okResult = requireReviewAssistOk(result);
    expect(okResult.data).toMatchObject({
      seededCount: 0,
      reportOnlyCount: 1,
      skippedSeedingReason: 'existing-human-draft',
    });
    const live = readLivePrReviewDraft({
      databasePath: paths.neondeckDatabase,
      repo: 'pandemicsyn/neondeck',
      prNumber: 10,
    });
    expect(live?.body).toBe('Human body');
    expect(live?.comments).toHaveLength(1);
    expect(live?.comments[0]).toMatchObject({
      body: 'Human inline comment',
      origin: 'human',
    });
  });

  it('rejects malformed structured output before writing reports or drafts', async () => {
    const paths = await tempPaths();
    const result = await reviewPrForHuman(
      { ref: 'pandemicsyn/neondeck#10' },
      paths,
      {
        fetchFacts: async () => reviewFacts(),
        reviewer: async () => ({ findings: [] }),
      },
    );

    expect(result).toMatchObject({
      ok: false,
      message: 'Review output did not match the expected schema.',
    });
    await expect(listReports(paths)).resolves.toEqual([]);
    expect(
      readLivePrReviewDraft({
        databasePath: paths.neondeckDatabase,
        repo: 'pandemicsyn/neondeck',
        prNumber: 10,
      }),
    ).toBeNull();
  });
});

async function tempPaths() {
  const home = await mkdtemp(join(tmpdir(), 'neondeck-pr-review-assist-'));
  tempRoots.push(home);
  const paths = runtimePaths(home);
  await ensureRuntimeHome(paths);
  return paths;
}

function reviewFacts(): ReviewAssistFacts {
  const state: GitHubPullRequestEventState = {
    repo: 'pandemicsyn/neondeck',
    number: 10,
    url: 'https://github.com/pandemicsyn/neondeck/pull/10',
    title: 'Add review assist',
    state: 'open',
    draft: false,
    merged: false,
    mergeCommitSha: null,
    headSha: 'head123',
    headRef: 'feature/review',
    baseRef: 'main',
    baseSha: 'base123',
    mergeable: true,
    mergeableState: 'clean',
    maintainerCanModify: true,
    commits: [],
    reviewThreads: [],
    requestedChangesReviews: [],
    requestedChangesState: {
      active: [],
      latestByReviewer: [],
      history: [],
    },
    checkSuites: [],
    checkRuns: [],
    branchPermissions: {
      headRepoFullName: 'pandemicsyn/neondeck',
      baseRepoFullName: 'pandemicsyn/neondeck',
      isFork: false,
      maintainerCanModify: true,
      headRepoPush: true,
      baseRepoPush: false,
      canLikelyPush: true,
      checkedAt: '2026-07-05T12:00:00.000Z',
    },
    isOutOfDate: false,
    fetchedAt: '2026-07-05T12:00:00.000Z',
  };
  const files: GitHubPullRequestFile[] = [
    {
      path: 'src/app.ts',
      previousPath: null,
      status: 'modified',
      additions: 2,
      deletions: 0,
      changes: 2,
      binary: false,
      generatedLike: false,
      patch: [
        '@@ -1,2 +1,3 @@',
        ' const keep = true;',
        '+const added = true;',
        ' export { keep };',
      ].join('\n'),
      truncated: false,
      sha: 'file123',
      htmlUrl: null,
      rawUrl: null,
      contentsUrl: null,
      message: null,
    },
  ];
  const diffSummary: GitHubDiffSummary = {
    files: 1,
    additions: 2,
    deletions: 0,
    binaryFiles: 0,
  };
  return {
    target: {
      repoFullName: 'pandemicsyn/neondeck',
      owner: 'pandemicsyn',
      repo: 'neondeck',
      number: 10,
    },
    state,
    files,
    diffSummary,
  };
}

function requireReviewAssistOk(
  result: Awaited<ReturnType<typeof reviewPrForHuman>>,
) {
  if (!result.ok || !('data' in result)) throw new Error(result.message);
  return result;
}

function reviewOutputWithOneFinding() {
  return {
    overview: {
      summary: 'Review summary',
      changeMap: [{ path: 'src/app.ts', summary: 'Modified source file.' }],
      risks: [],
      checks: ['No failing check runs were present in fetched facts.'],
    },
    findings: [
      {
        severity: 'major',
        path: 'src/app.ts',
        side: 'RIGHT',
        line: 2,
        summary: 'Validate the new branch.',
        suggestedFix: 'Add an explicit guard.',
      },
    ],
  };
}
